### ISSUE TITLE
Issue Cover Images

### ISSUE THREAD

**Issue by robertkochmf** [ScragEnd/scrag-end-production#13]
@bjornrust Do we have better images for these? Currently we are using a photograph of an issue, it would be nice to mockup a digital version.

**Comment by bjornrust** [comment]
Absolutely. I bounced them out some time ago. I'll email them to you tomorrow.

**Comment by robertkochmf** [comment]
Nice! I'm working from home today if you have a chance to shoot them through I can get this all finished.
