### ISSUE TITLE
Design and Develop Colophon Footer

### ISSUE THREAD

**Issue by robertkochmf** [ScragEnd/scrag-end-production#3]

**Comment by robertkochmf** [comment]
@bjornrust Would you be able to provide me with some of the content that would need to appear in the footer? I just want to have the complete understanding of the content requirements before laying it out.

**Comment by robertkochmf** [comment]
@bjornrust How do you feel about this? 

![home 2x](https://cloud.githubusercontent.com/assets/14832161/22200867/2ce83b26-e1b5-11e6-9f8d-25beace339bb.jpg)

**Comment by bjornrust** [comment]
That's basically the right direction.
